module.exports = {
    GET_MONEY_BACKEND_SUCCESS: 'GET_MONEY_BACKEND_SUCCESS',
    GET_MONEY_BACKEND_ERROR: 'GET_MONEY_BACKEND_ERROR',

    SEND_EMAIL_SUCCESS: 'SEND_EMAIL_SUCCESS',
    SEND_EMAIL_ERROR: 'SEND_EMAIL_ERROR',    

    SEND_NOTIFICATION_EMAIL_ERROR: 'SEND_NOTIFICATION_EMAIL_ERROR',
    SEND_NOTIFICATION_EMAIL_SUCCESS: 'SEND_NOTIFICATION_EMAIL_SUCCESS',

    GET_PROFILE_INFO_SUCCESS: 'GET_PROFILE_INFO_SUCCESS',
    GET_PROFILE_INFO_ERROR: 'GET_PROFILE_INFO_ERROR',

    GET_PROFILE_LOGS_SUCCESS: 'GET_PROFILE_LOGS_SUCCESS',
    GET_PROFILE_LOGS_ERROR: 'GET_PROFILE_LOGS_ERROR',    

    ADD_PROFILE_LOG_SUCCESS: 'ADD_PROFILE_LOG_SUCCESS',
    ADD_PROFILE_LOG_ERROR: 'ADD_PROFILE_LOG_ERROR',

    UPDATE_PROFILE_SUCCESS: 'UPDATE_PROFILE_SUCCESS',
    UPDATE_PROFILE_ERROR: 'UPDATE_PROFILE_ERROR',    

    GET_DASHBOARD_SUCCESS: 'GET_DASHBOARD_SUCCESS',
    GET_DASHBOARD_ERROR: 'GET_DASHBOARD_ERROR',    

    GET_HISTORY_LATEST_SUCCESS: 'GET_HISTORY_LATEST_SUCCESS',
    GET_HISTORY_LATEST_ERROR: 'GET_HISTORY_LATEST_ERROR',    

    GET_HISTORY_ALL_SUCCESS: 'GET_HISTORY_ALL_SUCCESS',
    GET_HISTORY_ALL_ERROR: 'GET_HISTORY_ALL_ERROR',     

    GET_NEWS_LATEST_SUCCESS: 'GET_NEWS_LATEST_SUCCESS',
    GET_NEWS_LATEST_ERROR: 'GET_NEWS_LATEST_ERROR',     

    DELETE_HISTORY_SUCCESS: 'DELETE_HISTORY_SUCCESS',
    DELETE_HISTORY_ERROR: 'DELETE_HISTORY_ERROR',

    PAYOUT_SUCCESS: 'PAYOUT_SUCCESS',
    PAYOUT_ERROR: 'PAYOUT_ERROR',

    QUICK_PAYMENT_SUCCESS: 'QUICK_PAYMENT_SUCCESS',
    QUICK_PAYMENT_ERROR: 'QUICK_PAYMENT_ERROR',

    BUY_MONEY_SUCCESS: 'BUY_MONEY_SUCCESS',
    BUY_MONEY_ERROR: 'BUY_MONEY_ERROR',

    GET_ORDER_BOOK_SUCCESS: 'GET_ORDER_BOOK_SUCCESS',
    GET_ORDER_BOOK_ERROR: 'GET_ORDER_BOOK_ERROR',

    MONEY_PROCESS_SUCCESS: 'MONEY_PROCESS_SUCCESS',
    MONEY_PROCESS_ERROR: 'MONEY_PROCESS_ERROR',

    GET_CHART_DATA_ERROR: 'GET_CHART_DATA_ERROR',
    GET_CHART_DATA_SUCCESS: 'GET_CHART_DATA_SUCCESS'
};
